### ISSUE TITLE
Error creating rule engine

### ISSUE THREAD

**Issue by nmerkle** [protegeproject/swrlapi#16]
Hi all,

I try to use the SWRLAPI as it is described here: [https://github.com/protegeproject/swrlapi/wiki/SWRLRuleEngineAPI](). My source code looks as follows:
```
File f = null;
		try {
			f = querySPARQL();
		} catch (IOException e1) {
			e1.printStackTrace();
		}
		om = OWLManager.createOWLOntologyManager();
		try {
			ontology = om.loadOntologyFromOntologyDocument(f);
		} catch (OWLOntologyCreationException e) {
			e.printStackTrace();
		}
		ruleEngine = SWRLAPIFactory.createSWRLRuleEngine(ontology);
```
As I execute this, I get the following exception:

> Exception in thread "main" org.swrlapi.exceptions.SWRLRuleEngineException: Error creating rule engine Drools. Exception: java.lang.IllegalArgumentException. Message: could not get prefixed name for IRI http://localhost:8888/aicasys/index.php/Vorlage:Room
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:73)
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:43)
> 	at org.swrlapi.factory.SWRLAPIFactory.createSWRLRuleEngine(SWRLAPIFactory.java:79)
> 	at org.swrlapi.example.MyRuleEngine.<init>(Unknown Source)
> 	at org.swrlapi.example.SWRLAPIExample.main(SWRLAPIExample.java:17)
> Caused by: java.lang.IllegalArgumentException: could not get prefixed name for IRI http://localhost:8888/aicasys/index.php/Vorlage:Room
> 	at org.swrlapi.bridge.converters.TargetRuleEngineConverterBase.iri2PrefixedName(TargetRuleEngineConverterBase.java:30)
> 	at org.swrlapi.drools.converters.DroolsOWLEntity2NameConverter.convert(DroolsOWLEntity2NameConverter.java:34)
> 	at org.swrlapi.drools.converters.oo.DroolsOWLAxiom2AConverter.convert(DroolsOWLAxiom2AConverter.java:171)
> 	at org.swrlapi.drools.converters.oo.DroolsOWLAxiom2AConverter.visit(DroolsOWLAxiom2AConverter.java:590)
> 	at uk.ac.manchester.cs.owl.owlapi.OWLDeclarationAxiomImpl.accept(OWLDeclarationAxiomImpl.java:112)
> 	at org.swrlapi.drools.converters.oo.DroolsOWLAxiom2AConverter.convert(DroolsOWLAxiom2AConverter.java:570)
> 	at org.swrlapi.drools.core.DroolsSWRLRuleEngine.defineOWLAxiom(DroolsSWRLRuleEngine.java:217)
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngine.exportOWLAxioms2TargetRuleEngine(DefaultSWRLRuleAndQueryEngine.java:412)
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngine.importAssertedOWLAxioms(DefaultSWRLRuleAndQueryEngine.java:65)
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:66)

I have no idea what could be the reason. Because the mentioned IRI is resolved by its namespace prefix and is contained in the ontology file. 

Best,
N.

**Comment by martinjoconnor** [comment]
Can you post the OWL file. (GitHub does not allow .owl extensions but if you put a .txt extension on the file it will accept it.)

**Comment by nmerkle** [comment]
Hi, 
I attached the ontology as text file.
[ontology.txt](https://github.com/protegeproject/swrlapi/files/188132/ontology.txt)

**Comment by martinjoconnor** [comment]
This ontology has no SWRL rules or SQWRL queries.

**Comment by nmerkle** [comment]
Yes, because I create the rules during runtime as described here: [https://github.com/protegeproject/swrlapi/wiki/SWRLRuleEngineAPI]()

> The OWLAPI can be used to programmatically create SWRL rules for use with a rule engine. The SWRLAPI also provides a parser to parse a textual representation of a SWRL rule. Using this parser, a rule (which is represented by a class called SWRLAPIRule can be created as follows:

```
OWLOntologyManager ontologyManager = OWLManager.createOWLOntologyManager();
 OWLOntology ontology 
   = ontologyManager.loadOntologyFromOntologyDocument(new File("/ont/Ont1.owl"));
 
 // Create a SWRL rule engine using the SWRLAPI  
 SWRLRuleEngine ruleEngine = SWRLAPIFactory.createSWRLRuleEngine(ontology);
 
 // Create a SWRL rule  
 SWRLAPIRule rule = ruleEngine.createSWRLRule("IsAdult-Rule",
   "Person(?p) ^ hasAge(?p, ?age) ^ swrlb:greaterThan(?age, 17) -> Adult(?p)");
 
 // Run the rule engine
 ruleEngine.infer();
```

But before I can create rules it already fails as I try to create the SWRRuleEngine.

**Comment by martinjoconnor** [comment]
The SWRLAPI is failing on IRIs when the ':' character is used in the body of the IRI, e.g.,

http://localhost:8888/aicasys/index.php/Vorlage:Room
http://localhost:8888/aicasys/index.php/Spezial:RDF_exportieren/Attribut:Foaf:name

I will take a look at this over the weekend. 

Martin

**Comment by nmerkle** [comment]
Hi Martin,

thanks for having a look at it. 
Is there any progress regarding the support of ':' in IRIs?  As soon as you have fixed it, please let me know, so that I can udate my current SWRLAPI version.

Best
N.

**Comment by martinjoconnor** [comment]
There is a new 1.0.0-beta-42 version that fixes some issues relating to IRIs that have no default prefixed form. 

However, the format of your IRIs will likely cause many parser issues because the parser does not yet support OWL entity references via direct IRI use or via annotations (e.g., rdfs:label).

Martin

**Comment by nmerkle** [comment]
Hi Martin,

Thanks for fixing the issue with ':'. I tried the new version out, but now I have the issue that **foaf:member** causes the same error. See my my error messages below:

> Exception in thread "main" org.swrlapi.exceptions.SWRLRuleEngineException: Error creating rule engine Drools. Exception: java.lang.IllegalArgumentException. Message: could not get prefixed name for IRI http://xmlns.com/foaf/0.1/member
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:73)
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:43)
> 	at org.swrlapi.factory.SWRLAPIFactory.createSWRLRuleEngine(SWRLAPIFactory.java:79)
> 	at org.swrlapi.example.MyRuleEngine.<init>(MyRuleEngine.java:40)
> 	at org.swrlapi.example.SWRLAPIExample.main(SWRLAPIExample.java:17)
> Caused by: java.lang.IllegalArgumentException: could not get prefixed name for IRI http://xmlns.com/foaf/0.1/member
> 	at org.swrlapi.bridge.converters.TargetRuleEngineConverterBase.iri2PrefixedName(TargetRuleEngineConverterBase.java:30)
> 	at org.swrlapi.drools.converters.oo.DroolsOWLIndividual2IConverter.convert(DroolsOWLIndividual2IConverter.java:32)
> 	at org.swrlapi.drools.converters.oo.DroolsOWLAxiom2AConverter.convert(DroolsOWLAxiom2AConverter.java:221)
> 	at org.swrlapi.drools.converters.oo.DroolsOWLAxiom2AConverter.visit(DroolsOWLAxiom2AConverter.java:710)
> 	at uk.ac.manchester.cs.owl.owlapi.OWLDataPropertyAssertionAxiomImpl.accept(OWLDataPropertyAssertionAxiomImpl.java:119)
> 	at org.swrlapi.drools.converters.oo.DroolsOWLAxiom2AConverter.convert(DroolsOWLAxiom2AConverter.java:570)
> 	at org.swrlapi.drools.core.DroolsSWRLRuleEngine.defineOWLAxiom(DroolsSWRLRuleEngine.java:217)
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngine.exportOWLAxioms2TargetRuleEngine(DefaultSWRLRuleAndQueryEngine.java:412)
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngine.importAssertedOWLAxioms(DefaultSWRLRuleAndQueryEngine.java:65)
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:66) 

It is as you said, now I have problems to use OWL entity references via direct IRI or via annotations (in this case, foaf:member). Is it planned to fix this issue in further iterations?

Best,
N.

**Comment by csnyulas** [comment]
You need to declare the `foaf` prefix in your ontology (in the Ontology Prefixes view on the Active Ontology tab).

**Comment by martinjoconnor** [comment]
Can you post the offending ontology. The ontology above worked for me.

As Csongor says, generating a prefix for foaf will help. If you generate appropriate prefixes for all entities in your ontology then you may have fewer issue - even though the SWRLAPI tries to auto-generate prefixes when none are defined.

However, many of your entity IRIs have characters that could only be parsed as direct IRI or via indirect annotation references (e.g., ```<something>:()_2```).

I plan to add IRI and annotation references to the parser in future but there is no timeline for that work.

**Comment by nmerkle** [comment]
Here is the offending ontology: [ontology.txt](https://github.com/protegeproject/swrlapi/files/194101/ontology.txt)

When I query the ontology I add in my sparql query the prefixes. So the prefix for foaf normally should be generated.

**Comment by martinjoconnor** [comment]
This ontology works for me (with the latest 1.0.0-beta-42). 

Defining prefixes for all namespaces in your ontology can make it more readable/understandable for others. For example, if I make the following SQWRL query:

    owl:Thing(?x) -> sqwrl:select(?x)

I get this result:

![screen shot 2016-03-29 at 9 37 30 pm](https://cloud.githubusercontent.com/assets/1731323/14132115/cfcb56c6-f5f6-11e5-9acc-006a75161d75.png)

The ```autogen``` prefixes are the SWRLAPI's attempt to make a useful prefixed form because no prefixes are defined for the relevant namespaces in the ontology. (Note that the underlying IRI can be extracted via the API; see [1] and [2]).

Martin

[1] https://github.com/protegeproject/swrlapi/wiki/SQWRLQueryAPI
[2] https://github.com/protegeproject/swrlapi/blob/master/src/main/java/org/swrlapi/sqwrl/values/SQWRLEntityResultValue.java

**Comment by nmerkle** [comment]
Hi,

I used the swrl-example project see here: [https://github.com/protegeproject/swrlapi-example]() and tried to add the  the latest 1.0.0-beta-42 version. Maybe there I made a mistake. What do I have to change in my example-project to add the new swrl-api version? Do I have to change something at the pom files?

N.

**Comment by nmerkle** [comment]
Now it worked. I have changed the dependency at my swrl-example pom to the right swrl-api version. But now I have another problem when I try to add my generated rules. 
`Action(Switch_Light_on) ^ AmbientLightSensor(?ambie) ^ AssistedPerson(?u) ^ EyeTrackingGlass(?e) ^ Intention(Switch_Light_On_Intention) ^ Lamp(?l) ^ HasAction(Switch_Light_On_Intention, Switch_Light_on) ^ HasInFocus(?e, ?l) ^ HasState(?ambie, ?ambientState) ^ HasState(?l, "off") ^ swrlb:greaterThan(?ambientState , 500) -> HasIntention(?u, Switch_Light_On_Intention)`
I get a SWRLParserException: 

> org.swrlapi.parser.SWRLParseException: Invalid SWRL atom predicate 'Action'
> 	at org.swrlapi.parser.SWRLParser.generateEndOfRuleException(SWRLParser.java:458)
> 	at org.swrlapi.parser.SWRLParser.parseSWRLAtom(SWRLParser.java:206)
> 	at org.swrlapi.parser.SWRLParser.parseSWRLRule(SWRLParser.java:105)
> 	at org.swrlapi.factory.DefaultSWRLAPIOWLOntology.createSWRLRule(DefaultSWRLAPIOWLOntology.java:217)
> 	at org.swrlapi.factory.DefaultSWRLAPIOWLOntology.createSWRLRule(DefaultSWRLAPIOWLOntology.java:211)
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngine.createSWRLRule(DefaultSWRLRuleAndQueryEngine.java:247)
> 	at org.swrlapi.example.MyRuleEngine.<init>(MyRuleEngine.java:73)
> 	at org.swrlapi.example.SWRLAPIExample.main(SWRLAPIExample.java:17)
> Rule: Action(Switch_Light_on) ^ AmbientLightSensor(?ambie) ^ AssistedPerson(?u) ^ EyeTrackingGlass(?e) ^ Intention(Switch_Light_On_Intention) ^ Lamp(?l) ^ HasAction(Switch_Light_On_Intention, Switch_Light_on) ^ HasInFocus(?e, ?l) ^ HasState(?ambie, ?ambientState) ^ HasState(?l, "off") ^ swrlb:greaterThan(?ambientState , 500) -> HasIntention(?u, Switch_Light_On_Intention)
> org.swrlapi.parser.SWRLParseException: Invalid SWRL atom predicate 'Action'
> 	at org.swrlapi.parser.SWRLParser.generateEndOfRuleException(SWRLParser.java:458)
> 	at org.swrlapi.parser.SWRLParser.parseSWRLAtom(SWRLParser.java:206)
> 	at org.swrlapi.parser.SWRLParser.parseSWRLRule(SWRLParser.java:105)
> 	at org.swrlapi.factory.DefaultSWRLAPIOWLOntology.createSWRLRule(DefaultSWRLAPIOWLOntology.java:217)
> 	at org.swrlapi.factory.DefaultSWRLAPIOWLOntology.createSWRLRule(DefaultSWRLAPIOWLOntology.java:211)
> 	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngine.createSWRLRule(DefaultSWRLRuleAndQueryEngine.java:247)
> 	at org.swrlapi.example.MyRuleEngine.<init>(MyRuleEngine.java:73)
> 	at org.swrlapi.example.SWRLAPIExample.main(SWRLAPIExample.java:17)

I tried to create rules with prefixes, but this also did not work. What could be the problem?

**Comment by martinjoconnor** [comment]
To use the non-prefixed form of an OWL entity name you will have to set its namespace to be the default ontology prefix. For example, for the IRI ```https://koralle27.fzi.de/aicasys/ontology#Action``` the default prefix must map to the ```https://koralle27.fzi.de/aicasys/ontology#``` namespace in order to use ```Action``` alone.

Take a look at the standalone SWRLTab [1]. It has an interactive rule and query editor that performs checking as you type - and also has auto-complete functionality.

Martin

[1] https://github.com/protegeproject/swrltab

**Comment by nmerkle** [comment]
Ok, thanks for your support. Now everything worked. :+1: 
I can finally apply my rules with the swrl api and the given ontology. :)

Best,
N.

**Comment by martinjoconnor** [comment]
Great!
