### ISSUE TITLE
SQWRL concurrency

### ISSUE THREAD

**Issue by jkyberneees** [protegeproject/swrlapi#17]
Hi Team, I noticed an issue related to the concurrent executions of queries using the SQWRLQueryEngine. 
If I try to execute a second query during the execution of the first, I get the following exception:

> org.swrlapi.sqwrl.exceptions.SQWRLException: error running SQWRL queries: error inserting asserted OWL axioms into Drools:\nIllegal method call. This session was previously disposed.

Is the SQWRLQueryEngine considered to be used under heavy load? Means, multi-user environment with high level of concurrency?

Looking forward to your hints,
Best Regards, Rolando.

**Comment by martinjoconnor** [comment]
If you create a new OWLAPI OWLOntology instance and and new SWRLAPI query or rule engine you should be able to run rules or queries in parallel. However, you cannot run rules or queries in parallel using the same rule or query engine.

See, for example, the integration tests, e.g.,

https://github.com/protegeproject/swrlapi-integration-tests/blob/master/src/test/java/org/swrlapi/SWRLBuiltInsIT.java

**Comment by jkyberneees** [comment]
Thanks for your explanation, now I understand the problem.
