### ISSUE TITLE
SQWRL engine warmup

### ISSUE THREAD

**Issue by jkyberneees** [protegeproject/swrlapi#18]
Hi Team, I have noticed that each query, even if these are performed on empty ontologies, take a considerable response time. 

Using a machine with an i7-6500U, 16GB RAM:

> A(?i) -> sqwrl:select(?i): When the ontology is empty takes ~340ms

Is there any clue for optimization? Please consider that the query engine was previously instantiated and this measurement considers only the query execution.

Best Regards,
Rolando

**Comment by martinjoconnor** [comment]
Are you talking about GUI-based use or API-based use?

**Comment by jkyberneees** [comment]
API based usage.

**Comment by martinjoconnor** [comment]
If the underlying OWL ontology changes between query runs then the underlying Drools rule engine is reset and all OWL axioms, rules, and queries are transformed again to their Drools representation. The rule engine reset process seems to take ~300 milliseconds on even a quite fast machine.

If the underlying ontology does not change (i.e., all rules, queries and axioms do not change) then subsequent queries should run quickly.

**Comment by jkyberneees** [comment]
Thanks martinjoconnor for your quick support and proper explanations. 
It seems that the current implementation of the SQWRLQueryEngine is not appropriated when performance and concurrency is mandatory. 
I have some other measurements already which show an slow performance while performing even basic queries. Here I share with you for your consideration:

**Testing the SQWRL engine (same machine than previous example):**

> NOTE: A and B extends from ParentClass

- A(?i) -> sqwrl:select(?i): When the ontology is empty takes ~340ms.
  - With 1000 individuals from class A takes: ~640ms.
  - With 2000 individuals from class A takes: ~815ms.
- ParentClass(?i) -> sqwrl:select(?i): When ontology is empty takes ~340ms
  - With 2000 individuals (from classes A and B) takes: ~910ms
- A(?i) ^ sqwrl:makeSet(?s, ?i) ^ sqwrl:size(?size, ?s) -> sqwrl:select(?size): With 1000 individuals on class A takes: ~1500ms
- ParentClass(?i) ^ sqwrl:makeSet(?s, ?i) ^ sqwrl:size(?size, ?s) -> sqwrl:select(?size): With 2000 individuals takes: ~1200ms

Anyway we keep looking forward to next releases and the evolution of this great library. 
Thanks Again, 
Rolando

**Comment by martinjoconnor** [comment]
Concurrency is supported (see #17) but performance has not been a major goal.

SQWRL queries operate not just on asserted knowledge but on reasoner-inferred knowledge (via an OWL 2 RL-based reasoner). OWL-based reasoning is relatively expensive in general, even when optimized. 

See the following paper for a discussion of the type of reasoning performed:

http://ceur-ws.org/Vol-849/paper_31.pdf
