### ISSUE TITLE
SWRLBuiltInBridge - defining a new built in in Java with OWL API

### ISSUE THREAD

**Issue by Meylina** [protegeproject/swrlapi#19]
Hello,

I have an issue with the SWRLBuiltInBridge. I have created a class "SWRLBuiltInLibraryImpl" in the package org.swrlapi.builtins.custom as indicated in the documentation. When I run the program, I have an OWLRuntimeException: "Exception in thread "main" org.semanticweb.owlapi.model.OWLRuntimeException: Prefix not registered for prefix name: custom:". 
To fix it, I tried to export the package as a jar file and to add it to the class path (I use Maven). I got the same error.
With Maven I do not manage dependencies, thus I would like to avoid opening the SWRL library sources to add the new package. And that's not very dynamic. Do I miss a step to add my new package without having to modify the SWRL library?

Thank you for your help.

**Comment by martinjoconnor** [comment]
Have you specified the ```custom``` prefix on your OWL ontology? You also need to define the individual built-ins at the OWL level.

See:

https://github.com/protegeproject/swrlapi/wiki/SWRLBuiltInBridge#defining-built-ins-in-owl

**Comment by Meylina** [comment]
Thank you for the tips. It works! Anyway, maybe you should describe the steps more accurately. It took me a long time to get it right.

**Comment by martinjoconnor** [comment]
Can you point out the inaccuracies.

**Comment by Meylina** [comment]
The part _Defining Built-Ins in Java_ is well explained. I had no problem to create the new builtin class in Java.
For OWL, I would explain the steps with an example (it is with OWL API):
	```
private void initRuleEngine(){
		OWLDocumentFormat format = manager.getOntologyFormat(ontology);
		PrefixDocumentFormat prefix = format.asPrefixOWLOntologyFormat();
		prefix.setPrefix(prefixNameBuiltIn, NSBuiltIn);
		
		ruleEngine = SWRLAPIFactory.createSWRLRuleEngine(ontology);
		ruleEngine.addSWRLBuiltIn(IRI.create(NSBuiltIn, newBuiltInName));
	}
```
I would also point out that it is needed to specify the new prefix before creating the rule engine, otherwise it is not taken into account. Finally, I have noticed that it works without creating an OWL ontology with the "Builtin" class and the builtin names as instances.

**Comment by martinjoconnor** [comment]
I have never tried the above approach. Normally the user would define a standalone ontology containing built-in definitions. They would then import that ontology and set its prefix appropriately.

Did this work without defining any ontology with built-in instances?

**Comment by Meylina** [comment]
Ok I see your point. Nevertheless, correct me if I am wrong but you still need to import the built-in ontology in your application. It is maybe easier than adding the prefix but you have an additional file which is not needed in the approach I have implemented. Anyway it is still interesting to know that both are possible.

**Comment by martinjoconnor** [comment]
Yup - definitely interesting that both work, and may make sense for your use case.

However, I would not want to encourage the approach you took in general. The associated OWL file is essentially the specification for the built-in library (see [1] for a set of these for the SWRLAPI built-in libraries and for the core SWRL built-in library). Without this specification a user must essentially manually define this specification in code in every application that uses the library. It would also mean that the library could not be used from within the Protege desktop application because it would have no way of resolving the built-ins in the library. 

[1] https://github.com/protegeproject/swrlapi/tree/master/src/main/resources/owl

**Comment by yu-zhang** [comment]
Could you show me the MyTemporal.owl? I can not find it in the https://github.com/protegeproject/swrlapi/wiki/SWRLBuiltInBridge#SWRL_BuiltIns.

By the way, whether this user defined built in can be used in OWLAPI pellete reasoner?

**Comment by yu-zhang** [comment]
I just download git clone the git clone https://github.com/protegeproject/swrlapi.git and build successful. I am using pellet reasoner by PelletReasoner reasoner = PelletReasonerFactory.getInstance().createReasoner(ontology) to do the reasoning. How to use the new added builtin, for example, the method defined in temporal in my code?
