### ISSUE TITLE
Getting "invalid datatype name 'rdf:PlainLiteral'"

### ISSUE THREAD

**Issue by lampdev** [protegeproject/swrlapi#20]
When creating a query in SQWRL tab like 

`DataPropertyName(?x, "FILE"^^rdf:PlainLiteral) -> sqwrl:select(?x)`

getting an error in "Status" box saying "invalid datatype name 'rdf:PlainLiteral'", however, the ontology contains proper rdf namespace URI and the literals are created as

`<Literal datatypeIRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral">FILE</Literal>`

**Comment by martinjoconnor** [comment]
It looks like is missed this (and rdfs:Literal and rdf:XMLLiteral). They are there now on the development branch. I will do a new release to master later today.

**Comment by lampdev** [comment]
Thanks Martin, appreciate it!

**Comment by martinjoconnor** [comment]
New 1.0.9 release of SWRLAPI and the Protege plugin on Maven Central.

**Comment by lampdev** [comment]
@martinjoconnor: Thanks, BTW, can confirm it works in development (1.0.10), just compiled the plugin and installed it. Thanks for the hint and such a quick fix!
