### ISSUE TITLE
Change the state of a DefaultSWRLAPIRule to inactive

### ISSUE THREAD

**Issue by DaliMidou** [protegeproject/swrlapi#21]
Hi,
I did not find a way to change the state of a DefaultSWRLAPIRule to inactive (active = false)

**Comment by martinjoconnor** [comment]
Looks like that method is missing on the SWRLAPIRule interface. I will fix shortly and get it into the next release.

**Comment by DaliMidou** [comment]
Thank you,
So with
swrlRuleEngine.infer();
all the SWRL rules in the ontology will be executed (because all the rules are active)

**Comment by martinjoconnor** [comment]
Yes. It examines the active state but clearly this will never change from its initial true value.

**Comment by DaliMidou** [comment]
Thank you
