### ISSUE TITLE
SWRL Plugin reshuffles the classes

### ISSUE THREAD

**Issue by Maschine723** [protegeproject/swrlapi#22]
Hello,

when I create a rule with SWRL Tab in Protege 5.0 and start/translate the rule into OWL some subclasses become mainclasses.

For example: before: Food (-> Pizza (-> Pizza Salami)
after: Food (-> Pizza (-> Pizza Salami) AND -> Pizza Salami)

"->" stands for "has subclass"

Did anyone have the same problem?

Thanks for helping

**Comment by martinjoconnor** [comment]
I don't fully follow the above. Do you have a simple OWL ontology that illustrates this behaviour?

**Comment by Maschine723** [comment]
Yeah, I have a simple OWL ontology and when I create a rule the classes seem to be reshuffled.

**Comment by martinjoconnor** [comment]
Can you post the ontology here. (You may need to change the extension to .txt from .owl.)

**Comment by Maschine723** [comment]
Sry I`m new here. How can I post an ontology?

**Comment by martinjoconnor** [comment]
When you are writing an issues the text "Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard" should appear below. Clock on the "selecting them" link to pick a file for upload.

**Comment by Maschine723** [comment]
[FunktionalNeu.zip](https://github.com/protegeproject/swrlapi/files/354742/FunktionalNeu.zip)

**Comment by martinjoconnor** [comment]
This ontology is empty.

**Comment by Maschine723** [comment]
[FunktionalNeu.zip](https://github.com/protegeproject/swrlapi/files/355664/FunktionalNeu.zip)

Does it work now?

**Comment by Maschine723** [comment]
I changed the extension into .txt but it didn´t work.

I found out that the problem only occurs, when a class is subclass of a class

**Comment by martinjoconnor** [comment]
A lot of seemingly redundant inferences are made when a reasoner is executed. Protege has a reasoner interface that distinguishes these inferences from original asserted statements in the ontology. This interface is used by common reasoners (Fact++, Pellet, etc.) but is not yet used by the OWL 2 RL reasoner in the SWRLTab plugin. 

If you are doing basic SWRL reasoning I would use one of the integrated reasoners for reasoning (though you can still used the SWRLTab's editor for creating rules). If you require some of the built-ins in the SWRLAPI's built-in library or wish to use SQWRL I would used the SWRLTab plugin's reasoner.
