### ISSUE TITLE
sqwrl and reasoners

### ISSUE THREAD

**Issue by ChipNowacek** [protegeproject/swrlapi#29]
Noob question: Does SQWRL do its own inferencing work or does it somehow rely on an active reasoner (hermit, pellet etc)

**Comment by martinjoconnor** [comment]
The SWRLAPI includes an implementation of an OWL 2 RL-based reasoner: 

https://github.com/protegeproject/swrlapi/wiki/OWL2RLTab

Hermit, Pellet, and other reasoners support SWRL but they do not support SQWRL. 

FYI, the Protege mailing list is a good place for further questions if you intend to spend more time with Protege:

http://protege.stanford.edu/support.php#mailingListSupport

**Comment by ChipNowacek** [comment]
Thank you. While I do participate on the Protege mailing list, I asked my question here because I'm trying to add query capacity to Tawny OWL. Maybe my thinking is flawed. I will ask there first next time.

Again, thank you.

**Comment by martinjoconnor** [comment]
Either place will do, though you might get more general responses on the mailing list.

While SQWRL is conceptually just SWRL with a custom built-in library there are some complexities to consider if you were to develop an implementation. 

You could start here to get a sense of how the SWRLAPI implements the SQWRL query language:

https://github.com/protegeproject/swrlapi/blob/master/src/main/java/org/swrlapi/sqwrl/SQWRLQueryEngine.java
