### ISSUE TITLE
temporal:duration + Pellet Reasoner

### ISSUE THREAD

**Issue by pauloprsdesouza** [protegeproject/swrlapi#38]
Hello,
I am passing through a problem with the built-in temporal: duration, the Pellet reasoner can not generate the inference when using built-in temporal: duration, but when I use Drools it succeeds in inferring. What can I do to make the inference using Pellet?

**Comment by martinjoconnor** [comment]
The SWRLAPI's custom built-in libraries can not be used by other reasoners.

All other OWL reasoners that I am aware of support only the core SWRL built-in library.
