### ISSUE TITLE
SWRLTAB JAR file for Protégé Plugin

### ISSUE THREAD

**Issue by wrjih** [protegeproject/swrlapi#4]
I am a Protégé user and want to use the SWRLTAB.  However, I have problem on install the Maven and cannot build the JAR file.   Is it possible for you to support the SWRLTAB JAR file for the Protégé user?

**Comment by martinjoconnor** [comment]
The [SWRLTab Plugin](https://github.com/protegeproject/swrltab-plugin) is built using the latest 4.0.2 version of the OWLAPI. Protégé 5.0 has not yet been updated to use the version of the OWLAPI so the plugin cannot be released until that updates it made. Work has already started on that update and should be available some time in May.
