### ISSUE TITLE
Custom datatype support

### ISSUE THREAD

**Issue by thelesenok** [protegeproject/swrlapi#46]
I can not create SWRL rule with custom datatype.

For example: 
**Rule:**
`Executor(?object) ^ executorAge(?object, ?prop0) ^ swrlb:matches(?prop0, "20.0"^^xsd:customdatatype) -> Executor(Analyst)`
**Rule:**
`Executor(?object) ^ executorAge(?object, ?prop0) ^ swrlb:matches(?prop0, ""^^xsd:customdatatype) -> Executor(Analyst)`
**Datatype:**
name: xsd:customdatatype
datatype definition:
`(xsd:double[>= "15.0"^^xsd:double] and xsd:double[<= "40.0"^^xsd:double])`

Error:
`invalid datatype name 'xsd:customdatatype'`
![2018-05-17 23 07 30](https://user-images.githubusercontent.com/39387017/40201234-2a0b602c-5a27-11e8-96cd-f0ac0c2b4516.png)

**Comment by cedaradmin** [comment]
Sorry - missed this question. Unfortunately, only the types supported by the OWLAPI are handled:

http://owlcs.github.io/owlapi/apidocs_5/org/semanticweb/owlapi/vocab/XSDVocabulary.html
