### ISSUE TITLE
Problem with using SQWRL Query engine

### ISSUE THREAD

**Issue by nehajain10** [protegeproject/swrlapi#52]
I am trying to run a query but the Query engine to throwing the error "Exception running SQWRL query S58: error running SQWRL queries: error exporting SQWRL query rule engine: A maximum of 11 can be passed to built-ins: error exporting SQWRL query rule engine: A maximum of 11 can be passed to built-ins: A maximum of 11 can be passed to built-ins". Kindly help me with what is the system referring to by this 11?

**Comment by martinjoconnor** [comment]
I'm guessing that you are trying to pass more than 11 arguments to a built-in? The implementation limit is 11 at the moment.

I will fix the error message so that it is clearer.
