### ISSUE TITLE
Cannot apply temporal:duration on swrl rules

### ISSUE THREAD

**Issue by Elsenosy** [protegeproject/swrlapi#55]
Hello,
I was build a SWRL depends on time interval between two values, for example:
`RUN(?ru) ^ temporal:duration(2, ?time1, ?time2, "seconds") -> CB_On(?ru)`
to infer an object under CB_On type after 2 seconds,
I tried to test this rule in the SQWRL tab, it works well, but when i use this rule in SWRL tab, there is no inferred objects! 
Many thanks in advance.

**Comment by martinjoconnor** [comment]
Can you post the ontology containing this rule. (Add '.txt' as extension since GitHub does not support OWL files.)
