### ISSUE TITLE
[Question] Replace a data property value with SWRL ?

### ISSUE THREAD

**Issue by thomakl** [protegeproject/swrlapi#58]
Hi,
I read a lot of posts mentioning that SWRL does not support data property values replacement ([See link from 2015](http://protege-project.136.n4.nabble.com/SWRL-ability-to-update-modify-data-property-td4663929.html)).
Is there a way around to do it (since then) ? 

Thank you for your time,

**Comment by martinjoconnor** [comment]
I would post these sorts of questions to the Protege mailing list:

https://protege.stanford.edu/support.php

There is a large community there that can offer a range of answers to questions like this.

To answer your question: like OWL, SWRL supports monotonic reasoning only. It would not really be the appropriate language to do what you are trying to do here.

See:

https://github.com/protegeproject/swrlapi/wiki/SWRLLanguageFAQ#Does_SWRL_support_Nonmonotonic_Inference

**Comment by thomakl** [comment]
I see. I'll try to ask the community about a way to counter this restriction with other methods.
Thank you for your time,

**Comment by martinjoconnor** [comment]
I would first search the mailing list for previous discussions.

http://protege-project.136.n4.nabble.com/Protege-Users-f22950.html

A search for the term 'monotonic' could lead you to some relevant discussions.
