### ISSUE TITLE
Rule ran with SWRL API not inferred

### ISSUE THREAD

**Issue by thomakl** [protegeproject/swrlapi#59]
Hi,

I have a rule that adding a data property to an individual.
My rule is correctly inferred with Protege in the SWRLTab. I can see it in the ontology and in the number of the inferred axioms.
However when I run this rule, with those commands :

`System.out.println("number of axioms: "+mission.ruleEngine.getNumberOfInferredOWLAxioms());
mission.ruleEngine.infer();`

I tried to run the ruleEngine with the alternative commands :
- run()
- exportInferredOWLAxioms()
Same issue.

**Any idea ?**

**Comment by martinjoconnor** [comment]
I'm not following. What is the problem?

**Comment by thomakl** [comment]
Hi @martinjoconnor ,

I'm sorry I wasn't that clear in my previous post.
The issue is : When I instantiated my rule in the SWRLRuleEngine via the SWRL API in Java, the rule is integrated to my ontology but the SWRLRuleEngine.infer() does not infer my rule. 
That's odd because when I infer my rule via Protege everything works fine. The rule does infer from my rule.

You see my point ?

PS : I'm working with OWL API 4.2.8 and SWRL API 2.0.6
PPS: Does it matter if the swrlapi-drools-engine and the swrlapi doesn't have the same version ? I have swrlapi-drools-engine in 2.0.5

**Comment by thomakl** [comment]
I fixed my issue with changing the name of my exported ontology.
Still don't understand why the OWL Axiom wasn't created through the ruleEngine.

Thanks for help
