### ISSUE TITLE
Querying issue

### ISSUE THREAD

**Issue by jkyberneees** [protegeproject/swrlapi#7]
Hi [Developer], first off: congratulations for providing this new library that significantly improves the way we deal with OWL2 ontologies.

I started to test the SQWRLQueryEngine but it seems to fail with almost all ontologies on my side, I expect something is not correct in my environment, but I am using the latest source code and all the compilations were performed OK.

### My testing scenario:
The ontology:
```xml
<?xml version="1.0"?>
<Ontology xmlns="http://www.w3.org/2002/07/owl#"
     xml:base="http://jwebsocket.org/ontologies/Bar"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     ontologyIRI="http://jwebsocket.org/ontologies/Bar"
     versionIRI="1.0.0">
    <Prefix name="" IRI="http://www.w3.org/2002/07/owl#"/>
    <Prefix name="owl" IRI="http://www.w3.org/2002/07/owl#"/>
    <Prefix name="rdf" IRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
    <Prefix name="xml" IRI="http://www.w3.org/XML/1998/namespace"/>
    <Prefix name="xsd" IRI="http://www.w3.org/2001/XMLSchema#"/>
    <Prefix name="rdfs" IRI="http://www.w3.org/2000/01/rdf-schema#"/>
    <Prefix name="pizza" IRI="http://www.co-ode.org/ontologies/pizza/pizza.owl#"/>
    <Import>http://protege.stanford.edu/ontologies/pizza/pizza.owl</Import>
</Ontology>
```
The source code:
```java
SQWRLQueryEngine lEngine = SWRLAPIFactory.createSQWRLQueryEngine(OWLManager.createOWLOntologyManager().loadOntology(getOntologyPath()));
lEngine.createSQWRLQuery("Q1", "pizza:Country(?c)->sqwrl:select(?c)");
SQWRLResult lQResult = lEngine.runSQWRLQuery("Q1");
```
The error:
* org.swrlapi.sqwrl.exceptions.SQWRLException: error running SQWRL queries: error exporting SQWRL query rule engine: internal error generating Drools rule
rule "Q1" 
when 
   CAA(cid=="pizza:Country", $owl:c:i) 
then 
   invoker.invoke("Q1", "sqwrl:select", 0, true, $owl:c);  
end
[[3,35]: [ERR 102] Line 3:35 mismatched input ':' in rule "Q1", [0,0]: Parser returned a null Package]

Looking forward to your support, thanks in advance for your time.

Rolando SM
jWebSocket Framework Developer

**Comment by martinjoconnor** [comment]
The namespace of this ontology (http://www.w3.org/2002/07/owl#) is the OWL namespace itself. As a result, all entities (such as variables in SQWRL queries) are created in the same namespace of core OWL entities like Thing, which is leads to lots of internal confusion. It should be changed to something sensible.

While looking at this I found an unrelated bug in the Drools component (https://github.com/protegeproject/swrlapi-drools-engine), which I fixed. Pull the latest code from there, fix the namespace issue, and it should then work.

**Comment by jkyberneees** [comment]
Sorry for being so insistent, updates applied, ontology fixed:
```xml
<?xml version="1.0"?>
<Ontology xmlns="http://www.w3.org/2002/07/owl#"
     xml:base="http://jwebsocket.org/ontologies/Bar"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     ontologyIRI="http://jwebsocket.org/ontologies/Bar"
     versionIRI="1.0.0">
    <Prefix name="owl" IRI="http://www.w3.org/2002/07/owl#"/>
    <Prefix name="rdf" IRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
    <Prefix name="xml" IRI="http://www.w3.org/XML/1998/namespace"/>
    <Prefix name="xsd" IRI="http://www.w3.org/2001/XMLSchema#"/>
    <Prefix name="rdfs" IRI="http://www.w3.org/2000/01/rdf-schema#"/>
    <Prefix name="pizza" IRI="http://www.co-ode.org/ontologies/pizza/pizza.owl#"/>
    <Import>http://protege.stanford.edu/ontologies/pizza/pizza.owl</Import>
</Ontology>
```

Still receiving the same error ;(
* org.swrlapi.sqwrl.exceptions.SQWRLException: error running SQWRL queries: error exporting SQWRL query rule engine: internal error generating Drools rule
rule "Q1" 
when 
   CAA(cid=="pizza:Country", $owl:c:i) 
then 
   invoker.invoke("Q1", "sqwrl:select", 0, true, $owl:c);  
end
[[3,35]: [ERR 102] Line 3:35 mismatched input ':' in rule "Q1", [0,0]: Parser returned a null Package]

**Comment by martinjoconnor** [comment]
Still has namespace of OWL ontology. See line #2: xmlns=...

Martin

**Comment by jkyberneees** [comment]
Hi martinjoconnor, I just fixed the second line and all WORKED as expected, thanks for your support!!!
However the issue is produced by Protege itself, when I save the ontology as OWL/XML format. I will check if it still present in the OWLAPI 4.x

Best Regards,
Rolando

**Comment by jkyberneees** [comment]
The issue is produced with OWLAPI 3.x, 4.x when exporting to OWL/XML format.
The RDF/XML exports correct:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
    xmlns="http://jwebsocket.org/ontologies/Bar#"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:xml="http://www.w3.org/XML/1998/namespace"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">

<rdf:Description rdf:about="http://jwebsocket.org/ontologies/Bar">
    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Ontology"/>
    <owl:imports rdf:resource="http://protege.stanford.edu/ontologies/pizza/pizza.owl"/>
</rdf:Description>
<!-- Generated by the OWL API (version 4.1.0) http://owlapi.sourceforge.net -->
</rdf:RDF>
```

However when you save to OWL/XML the xmlns property is not set:
```xml
<?xml version="1.0"?>
<Ontology xmlns="http://www.w3.org/2002/07/owl#"
     xml:base="http://jwebsocket.org/ontologies/Bar"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     ontologyIRI="http://jwebsocket.org/ontologies/Bar">
    <Prefix name="owl" IRI="http://www.w3.org/2002/07/owl#"/>
    <Prefix name="rdf" IRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
    <Prefix name="xml" IRI="http://www.w3.org/XML/1998/namespace"/>
    <Prefix name="xsd" IRI="http://www.w3.org/2001/XMLSchema#"/>
    <Prefix name="rdfs" IRI="http://www.w3.org/2000/01/rdf-schema#"/>
    <Import>http://protege.stanford.edu/ontologies/pizza/pizza.owl</Import>
</Ontology>
<!-- Generated by the OWL API (version 4.1.0) http://owlapi.sourceforge.net -->
```
So, is this an issue in the OWLAPI?

**Comment by martinjoconnor** [comment]
This certainly looks suspect to me. I will follow up with Matthew Horridge, one of the OWLAPI developers (who will be back in the office Friday), to confirm.

By coincidence, we recently found a few issues dealing with SWRL rules that are saved using the OWL/XML serialization. If you plan to experiment with SWRL or SQWRL the RDF/XML serialization may be more stable. 

Note that this API is not officially released  - but should be pretty stable. If you find other SWRLAPI-related issues feel free to report them here and should be able to address them pretty quickly. If your questions are more 'ontological' you should post them to the Protege mailing list: http://protege.stanford.edu/support.php

**Comment by martinjoconnor** [comment]
I spoke with Matthew and he recommended not using the OWL/XML serialization for the moment. The RDF/XML serialization is far more common and robust.
