### ISSUE TITLE
Question about SWRLAPI in protege (Drools -> OWL)

### ISSUE THREAD

**Issue by xxwywzy** [protegeproject/swrlapi#71]
Hi, thank you for providing such a great tool for SWRL reasoning. When I was using it through protege, I found that when I click the Drools->OWL button to transfer the inferred rule engine knowledge to OWL knowledge, it seems like the original asserted class hierarchy will be destroyed (several classes will be moved into the same level). This problem will not happen when I use the Pellet reasoner. Is this a deliberate design or a bug? The version of protege is 5.5.0 on MacOS.

**Comment by martinjoconnor** [comment]
It's a feature. :) 

The SWRLAPI's reasoner implementation has not been completely integrated into Protege's reasoner framework so a lot of 'trivial' intermediate inferences will be visible after the inference process.

For your purposes, it may be better to use a reasoner like Pellet, which has been properly integrated. 

The SWRLAPI is most useful when using SQWRL queries or when you need its custom built-ins.

**Comment by xxwywzy** [comment]
> It's a feature. :)
> 
> The SWRLAPI's reasoner implementation has not been completely integrated into Protege's reasoner framework so a lot of 'trivial' intermediate inferences will be visible after the inference process.
> 
> For your purposes, it may be better to use a reasoner like Pellet, which has been properly integrated.
> 
> The SWRLAPI is most useful when using SQWRL queries or when you need its custom built-ins.

Got it! Thank you so much!
