### ISSUE TITLE
Loading of external built-ins fails

### ISSUE THREAD

**Issue by RalphBln** [protegeproject/swrlapi#74]
The URLClassLoader instance created in loadExternalSWRLBuiltInLibraries is not used and loading of custom built-in library classes fails.

**Comment by martinjoconnor** [comment]
Thanks for contributing this. 

Can you explain what the fix does?

**Comment by RalphBln** [comment]
Sure :)

The original code creates a URLClassLoader instance [in SWRLBuiltInLibraryManager, line 82](https://github.com/protegeproject/swrlapi/blob/a8df6e0a5a0ff5920d19d0fcda0517c32c13b68e/src/main/java/org/swrlapi/builtins/SWRLBuiltInLibraryManager.java#L82) but the instance is never used. In the fixed code, the instance is now passed to [instantiateSWRLBuiltInLibraryImplementation](https://github.com/protegeproject/swrlapi/blob/a8df6e0a5a0ff5920d19d0fcda0517c32c13b68e/src/main/java/org/swrlapi/builtins/SWRLBuiltInLibraryManager.java#L348) and actually used for loading the external library classes (otherwise they would not be found because the original classloader does not have the external library directories in its classpath, at least not if the swrlapi is used from the swrltab protege plug-in).

**Comment by martinjoconnor** [comment]
Great - thanks. I will merge this during the week. I'm not sure it will fix the entire issue here - I never properly finished the built-in loading task because OSGi hurt my head and I ran out of time, but this sounds like a necessary first step.
