### ISSUE TITLE
upgrade to owlapi-5.x

### ISSUE THREAD

**Issue by jicro** [protegeproject/swrlapi#80]
Since owlapi library has already upgrade to 5.x (latest version is 5.1.20), do we have a plan to upgrade the dependency owlapi lib to 5.x version? I tried to do this in my fork, but got many in-compatibilities.
If you have a plan to upgrade, I also pleasure to join this work. thx.

**Comment by martinjoconnor** [comment]
There are no plans. The v5 release of the OWLAPI is very different from previous versions and a considerable amount of work would be required. The v4 version of the API is still actively maintained, FYI.

**Comment by jicro** [comment]
thx ^_~
